---
# tasks file for lanceur_du_serveur_jenkins

# installer wget  --> # voir dans meta/main.yml 

# telecharger  et installer  java

# telecharger jenkins sur le web
- name: Download file with check (sha256)
  get_url:
    url: http://mirrors.jenkins.io/war/2.263/jenkins.war
    dest: /tmp/jenkins{{port}}.war
    mode: '0755'

# faire une ouverture de flux
- firewalld:
    port: {{port}}/tcp
    permanent: yes
    state: enabled
  notify:
    - firewalld - reload
# Mettre SeLinux en mode permissive

- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

#verifcation de l'ouverure de flux avant de lancer

# lancement de la commande pour lancer jenkins
- name: lancement de jenkins
  become: true
  shell: pkill java ; java -jar /tmp/jenkins.war --httpPort=9090 --logfile=/var/log/jenkins_log 2>&1 & 
