---
# tasks file for lanceur_du_serveur_jenkins

# installer wget  --> # voir dans meta/main.yml 

# telecharger  et installer  java

# telecharger jenkins sur le web
- name: Download file with check (sha256)
  get_url:
    url: http://mirrors.jenkins.io/war/2.263/jenkins.war
    dest: "/tmp/jenkins{{ item }}.war"
    mode: '0777'
    with_items:
      - 9091
      - 9092

# faire une ouverture de flux
- firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    with_items:
     - 9091
     - 9092 
notify:
    - firewalld - reload
# Mettre SeLinux en mode permissive

- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

#verifcation de l'ouverure de flux avant de lancer

# lancement de la commande pour lancer jenkins
- name: lancement de jenkins
  become: true
  shell: " pkill java ; java -jar /tmp/jenkins{{ item }}.war --httpPort={{ item }} --logfile=/var/log/jenkins{{ item }}_log 2>&1 & " 
  with_items:
    - 9091
    - 9092
